rtabmap:
  ros__parameters:
    frame_id: "base_footprint"
    subscribe_depth: true
    approx_sync: true
    Reg/Strategy: "0"
    Vis/MinInliers: "20"
    RGBD/ProximityBySpace: "False"
    RGBD/ProximityByTime: "True"
    wait_for_transform: 0.5

